class CreateBaanRawData < ActiveRecord::Migration
  def self.up
    create_table :baan_raw_data do |t|
      t.integer :baan_import_id
      t.string :baan_0
      t.string :baan_1
      t.string :baan_2
      t.string :baan_3
      t.string :baan_4
      t.string :baan_5
      t.string :baan_6
      t.string :baan_7
      t.string :baan_8
      t.string :baan_9
      t.string :baan_10
      t.string :baan_11
      t.string :baan_12
      t.string :baan_13
      t.string :baan_14
      t.string :baan_15
      t.string :baan_16
      t.string :baan_17
      t.string :baan_18
      t.string :baan_19
      t.string :baan_20
      t.string :baan_21
      t.string :baan_22
      t.string :baan_23
      t.string :baan_24
      t.string :baan_25
      t.string :baan_26
      t.string :baan_27
      t.string :baan_28
      t.string :baan_29
      t.string :baan_30
      t.string :baan_31
      t.string :baan_32
      t.string :baan_33
      t.string :baan_34
      t.string :baan_35
      t.string :baan_36
      t.string :baan_37
      t.string :baan_38
      t.string :baan_39
      t.string :baan_40
      t.string :baan_41
      t.string :baan_42
      t.string :baan_43
      t.string :baan_44
      t.string :baan_45
      t.string :baan_46
      t.string :baan_47
      t.string :baan_48
      t.string :baan_49
      t.string :baan_50
      t.string :baan_51
      t.string :baan_52
      t.string :baan_53
      t.string :baan_54
      t.string :baan_55
      t.string :baan_56
      t.string :baan_57
      t.string :baan_58
      t.string :baan_59
      t.string :baan_60
      t.string :baan_61
      t.string :baan_62
      t.string :baan_63
      t.string :baan_64
      t.string :baan_65
      t.string :baan_66
      t.string :baan_67
      t.string :baan_68
      t.string :baan_69
      t.string :baan_70
      t.string :baan_71
      t.string :baan_72
      t.string :baan_73
      t.string :baan_74
      t.string :baan_75
      t.string :baan_76
      t.string :baan_77
      t.string :baan_78
      t.string :baan_79
      t.string :baan_80
      t.string :baan_81
      t.timestamps
    end
  end

  def self.down
    drop_table :baan_raw_data
  end
end
